name: AutoOpen_Book
version: '${project.version}'
main: autoopen_book.autoopen_book.AutoOpen_Book
api-version: 1.17
description: Auto open book on join'
commands:
  pomoc:
    description: Otwórz książkę z listą pomocy
    usage: /pomoc