name: Autobook
version: '${project.version}'
main: pl.zs1.autobook.Main
api-version: 1.17
authors: [ Jakub_Wisniewski, Kacper_Lapka ]
description: Auto open book
website: https://zs1.nowotarski.edu.pl/
commands:
  pomoc:
    description: Otwórz książkę z listą pomocy
    usage: /pomoc